import Head from 'next/head'
import { useState } from "react"
import { Inter } from '@next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ingredients, setIngredients] = useState("") // 献立の材料 
  const [pfc, setPFC] = useState(false) // pfcを考慮するかどうか
  const [menu, setMenu] = useState([])

  const doSubmit = (e) => {
      fetch('http://localhost:5000/', {
          method: "POST",
          headers: {
              'Content-Type': 'application/json',
          },
          body: JSON.stringify(
              {
                  'ingredients': ingredients,
              }
          )
      })
      .then(res => res.json())
      .then(data => setMenu(data.menu))

      e.preventDefault()
  }

  const doChangePFC = (e) => {
    setPFC(e.target.checked)
  }

  const doChangeIngredients = (e) => {
      setIngredients(e.target.value)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <h1>材料入力</h1>
          <form onSubmit={doSubmit}>
              <label className='block mb-2 text-sm font-medium text-gray-900 dark:text-white'>冷蔵庫の中身の使いたい食材を入力してください（食材ごとに句点を入れてください）</label>
              <textarea className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" name="input" placeholder="例）じゃがいも、にんじん、牛乳" onChange={doChangeIngredients} />
              <div>
                  <input type="checkbox" onChange={doChangePFC} id="pfc-check"/>
                  <label htmlFor="fpc-check">PFCを気にする</label>
              </div>
              {pfc && 
                <div>
                    <div>
                        <label htmlFor="height">身長：</label>
                        <input type="text" id="height" placeholder="170" />
                    </div>
                    <div>
                        <label htmlFor="weight">体重：</label>
                        <input type="text" id="weight" placeholder="65" />
                    </div>
                </div>}
              <button className='bg-blue-500 hover:bg-blue-400 text-white rounded px-4 py-2'>検索</button>
          </form>
          {menu.length != 0 && 
            <div>
                <hr/>
                <h1>献立候補</h1>
                {menu.map((value, index) => 
                  <div key={index}>
                    <div>
                      <h5>「{value.dish}」</h5>
                      <h6>材料：{value.ingredients}</h6>
                      <p>レシピ：{value.recipe}</p>
                    </div>
                  </div>
                )}
                <button>他の候補を教えて</button>
            </div>}
      </div>
    </>
  )
}
